### PR TITLE
New update for the Bridge POD

### PR DESCRIPTION
**Pull request by joe-amendolara**
Regards from Joe

### CODE REVIEW

**Comment by joe-amendolara** [comment]
updated reviewer (forgot to add John)

**Review by jb-smoker — APPROVED** [review]
🚀

**Review by jb-smoker — COMMENTED** [review]
You've updated the document source, but will need to run `jb build`, copy the results to the ace-bridge folder, then commit those files for these changes to be published. Steps 6-9 from the readme.

**Review by jb-smoker — APPROVED** [review]
Perfect!

**Pull request merged**
